### ISSUE TITLE
镜像已经几天没有更新了

### ISSUE THREAD

**Issue by chenjunyu19** [dglinux/issues#20]
多数镜像的“上次更新”日期还停留在七月24日和25日。

**Comment by chenjunyu19** [comment]
2020-07-30 已恢复同步。

**Comment by korokor0** [comment]
Thank you for your attention to this matter.

The university’s firewall believed that our traffic was too large and might be under attack, so it blocked some of our download requests.

We have communicated to solve this problem, and since it's summer vacation now, we spent a little time on the process.  

Have a good one.
